from fastapi import APIRouter, Depends, HTTPException, Response
from sqlalchemy.orm import Session
from typing import List, Optional
from datetime import datetime

from app.core.database import get_db
from app.models.domain import Report, Profile, Project, Task, Sprint
from app.schemas.pydantic_models import ReportGenerateRequest
from app.api.deps import get_current_user
from app.services.report_service import ReportService

router = APIRouter(prefix="/reports", tags=["Reports"])

@router.get("")
def list_reports(db: Session = Depends(get_db), current_user: Profile = Depends(get_current_user)):
    reports = db.query(Report).order_by(Report.created_at.desc()).limit(20).all()
    res = []
    for r in reports:
        gen = db.query(Profile).filter(Profile.id == r.generated_by).first() if r.generated_by else None
        res.append({
            "id": r.id,
            "title": r.title,
            "report_type": r.report_type,
            "format": r.format,
            "generated_by_name": gen.full_name if gen else "System",
            "created_at": r.created_at
        })
    return res

@router.post("/generate")
def generate_report(req: ReportGenerateRequest, db: Session = Depends(get_db), current_user: Profile = Depends(get_current_user)):
    headers = ["Task Title", "Project", "Priority", "Status", "Progress", "Due Date"]
    tasks = db.query(Task).all()
    
    table_rows = []
    for t in tasks:
        p = db.query(Project).filter(Project.id == t.project_id).first()
        table_rows.append([
            t.title[:30],
            p.key if p else "N/A",
            t.priority,
            t.status,
            f"{t.progress}%",
            str(t.due_date or "N/A")
        ])

    file_format = req.format.upper()
    now_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")

    report_record = Report(
        title=req.title,
        report_type=req.report_type,
        format=file_format,
        generated_by=current_user.id,
        meta_data={"row_count": len(table_rows)}
    )
    db.add(report_record)
    db.commit()

    if file_format == "CSV":
        csv_data = ReportService.generate_csv_report(req.title, headers, table_rows)
        return Response(
            content=csv_data,
            media_type="text/csv",
            headers={"Content-Disposition": f"attachment; filename={req.title.replace(' ', '_')}.csv"}
        )
    elif file_format == "EXCEL":
        excel_data = ReportService.generate_excel_report(req.title, headers, table_rows)
        return Response(
            content=excel_data,
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": f"attachment; filename={req.title.replace(' ', '_')}.xlsx"}
        )
    else: # PDF
        summary = {
            "Total Scope": f"{len(tasks)} tasks",
            "Report Focus": req.report_type,
            "Generated By": current_user.full_name,
            "Target Organization": "SprintIQ Engineering"
        }
        pdf_data = ReportService.generate_pdf_report(req.title, now_str, summary, headers, table_rows)
        return Response(
            content=pdf_data,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename={req.title.replace(' ', '_')}.pdf"}
        )
