from fastapi import APIRouter, Depends, HTTPException, Response, Query
from sqlalchemy.orm import Session
from typing import List, Optional, Dict, Any
from datetime import datetime, timedelta

from app.core.database import get_db
from app.models.domain import Report, Profile, Project, Task, Sprint, ProjectMember
from app.schemas.pydantic_models import ReportGenerateRequest
from app.api.deps import get_current_user
from app.services.report_service import ReportService

router = APIRouter(prefix="/reports", tags=["Reports"])

def _parse_t_date(d):
    if not d:
        return None
    if isinstance(d, datetime):
        return d.date()
    if isinstance(d, str):
        try:
            return datetime.fromisoformat(d.replace("Z", "+00:00")).date()
        except Exception:
            try:
                return datetime.strptime(d[:10], "%Y-%m-%d").date()
            except Exception:
                return None
    return d

def _build_report_payload(
    db: Session,
    report_type: str,
    project_id: Optional[str],
    sprint_id: Optional[str],
    current_user: Profile
) -> Dict[str, Any]:
    rtype = (report_type or "SPRINT").upper()
    
    # Resolve target project
    project = None
    if project_id:
        project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        project = db.query(Project).first()
    p_id = project.id if project else None
    p_name = project.name if project else "SprintIQ Platform"

    # Resolve target sprint
    sprint = None
    if sprint_id:
        sprint = db.query(Sprint).filter(Sprint.id == sprint_id).first()
    if not sprint and p_id:
        sprint = db.query(Sprint).filter(Sprint.project_id == p_id, Sprint.status == "ACTIVE").first()
        if not sprint:
            sprint = db.query(Sprint).filter(Sprint.project_id == p_id).order_by(Sprint.created_at.desc()).first()

    today = datetime.utcnow().date()

    if rtype == "DEVELOPER":
        # Developer Task Allocation Report
        if p_id:
            members = db.query(ProjectMember).filter(ProjectMember.project_id == p_id).all()
            dev_ids = list({m.user_id for m in members if m.role_in_project.upper() == "DEVELOPER"})
            devs = db.query(Profile).filter(Profile.id.in_(dev_ids)).all() if dev_ids else []
        else:
            devs = db.query(Profile).join(Profile.role).filter(Profile.role.has(name="developer")).all()

        headers = ["Developer Name", "Email", "Assigned Tasks", "Completed", "In Review", "Workload Hours", "Capacity Status"]
        rows = []
        chart_data = []
        total_tasks_count = 0
        total_workload_hrs = 0.0

        for d in devs:
            t_query = db.query(Task).filter(Task.assigned_developer_id == d.id)
            if p_id:
                t_query = t_query.filter(Task.project_id == p_id)
            dev_tasks = t_query.all()
            
            assigned = len(dev_tasks)
            comp = len([t for t in dev_tasks if t.status == "COMPLETED"])
            rev = len([t for t in dev_tasks if t.status == "REVIEW_PENDING"])
            hrs = sum(t.estimated_hours or 0.0 for t in dev_tasks)
            total_tasks_count += assigned
            total_workload_hrs += hrs

            status = "OVERLOADED" if hrs > 40.0 else ("BALANCED" if hrs >= 15.0 else "AVAILABLE")
            rows.append([d.full_name, d.email, assigned, comp, rev, f"{hrs:.1f}h", status])
            chart_data.append({"name": d.full_name, "hours": round(hrs, 1), "tasks": assigned})

        summary = {
            "Report Type": "Developer Task Allocation",
            "Project": p_name,
            "Active Team Members": len(devs),
            "Total Assigned Tasks": total_tasks_count,
            "Total Workload Hours": f"{total_workload_hrs:.1f} hrs",
            "Generated By": current_user.full_name
        }
        title = f"Developer Task Allocation — {p_name}"

    elif rtype == "WEEKLY":
        # Weekly Team Summary
        tasks_query = db.query(Task)
        if p_id:
            tasks_query = tasks_query.filter(Task.project_id == p_id)
        tasks = tasks_query.all()

        headers = ["Task / Deliverable", "Assignee", "Priority", "Status", "Progress", "Due Date"]
        rows = []
        comp_count = 0
        delayed_count = 0
        for t in tasks:
            dev = db.query(Profile).filter(Profile.id == t.assigned_developer_id).first() if t.assigned_developer_id else None
            due = _parse_t_date(t.due_date)
            if t.status == "COMPLETED":
                comp_count += 1
            elif due and due < today:
                delayed_count += 1

            rows.append([
                t.title[:32],
                dev.full_name if dev else "Unassigned",
                t.priority,
                t.status,
                f"{t.progress or 0}%",
                str(due or "N/A")
            ])

        chart_data = [
            {"status": "Completed", "count": comp_count},
            {"status": "In Progress", "count": len([t for t in tasks if t.status == "IN_PROGRESS"])},
            {"status": "Review", "count": len([t for t in tasks if t.status == "REVIEW_PENDING"])},
            {"status": "Delayed", "count": delayed_count}
        ]

        summary = {
            "Report Type": "Weekly Team Summary",
            "Project": p_name,
            "Health Status": project.health_status if project else "HEALTHY",
            "Risk Score": f"{project.ai_risk_score if project else 18.5} / 100",
            "Completed Items": comp_count,
            "Delayed Items": delayed_count,
            "Total Scope": f"{len(tasks)} tasks",
            "Generated By": current_user.full_name
        }
        title = f"Weekly Team Summary — {p_name}"

    elif rtype == "PROJECT":
        # Project Health Portfolio Report
        all_projects = db.query(Project).all()
        headers = ["Project Name", "Project Key", "Manager", "Total Tasks", "Completed", "Progress", "Health", "AI Risk"]
        rows = []
        chart_data = []
        total_p_tasks = 0
        total_p_completed = 0

        for prj in all_projects:
            mgr = db.query(Profile).filter(Profile.id == prj.manager_id).first() if prj.manager_id else None
            p_tasks = db.query(Task).filter(Task.project_id == prj.id).all()
            t_cnt = len(p_tasks)
            c_cnt = len([t for t in p_tasks if t.status == "COMPLETED"])
            total_p_tasks += t_cnt
            total_p_completed += c_cnt
            pct = round((c_cnt / max(t_cnt, 1)) * 100, 1)
            risk = round(prj.ai_risk_score if prj.ai_risk_score is not None else 0.0, 1)
            health = (prj.health_status or "HEALTHY").upper()

            rows.append([
                prj.name,
                prj.key or "N/A",
                mgr.full_name if mgr else "Unassigned",
                t_cnt,
                c_cnt,
                f"{pct}%",
                health,
                f"{risk} / 100"
            ])
            chart_data.append({
                "name": prj.name,
                "progress": pct,
                "risk": risk
            })

        summary = {
            "Report Type": "Project Health Portfolio",
            "Total Tracked Projects": len(all_projects),
            "Total Scope Tasks": total_p_tasks,
            "Completed Tasks": total_p_completed,
            "Portfolio Completion": f"{round((total_p_completed / max(total_p_tasks, 1)) * 100, 1)}%",
            "Generated By": current_user.full_name
        }
        title = "Project Health Portfolio"

    else:
        # Default: SPRINT (Sprint Burndown & Velocity)
        sprint_name = sprint.name if sprint else "Active Sprint"
        t_query = db.query(Task)
        if sprint:
            t_query = t_query.filter(Task.sprint_id == sprint.id)
        elif p_id:
            t_query = t_query.filter(Task.project_id == p_id)
        tasks = t_query.all()

        headers = ["Task Title", "Story Pts", "Assignee", "Priority", "Status", "Progress", "Due Date"]
        rows = []
        total_pts = 0
        comp_pts = 0

        for t in tasks:
            dev = db.query(Profile).filter(Profile.id == t.assigned_developer_id).first() if t.assigned_developer_id else None
            pts = t.story_points or 1
            total_pts += pts
            if t.status == "COMPLETED":
                comp_pts += pts
            elif t.status == "REVIEW_PENDING":
                comp_pts += int(pts * 0.9)

            rows.append([
                t.title[:30],
                pts,
                dev.full_name if dev else "Unassigned",
                t.priority,
                t.status,
                f"{t.progress or 0}%",
                str(t.due_date or "N/A")
            ])

        # Burndown Chart data
        chart_data = []
        days_count = 7
        for i in range(days_count):
            ideal_val = max(0, round(total_pts * (1.0 - (i / (days_count - 1))), 1))
            fraction = min(1.0, i / max(1, days_count - 2))
            actual_val = max(0, round(total_pts - (comp_pts * fraction), 1))
            chart_data.append({"day": f"Day {i+1}", "ideal": ideal_val, "actual": actual_val})

        summary = {
            "Report Type": "Sprint Burndown & Velocity",
            "Project": p_name,
            "Sprint": sprint_name,
            "Total Story Points": total_pts,
            "Completed Points": comp_pts,
            "Velocity Adherence": f"{round((comp_pts / max(total_pts, 1)) * 100, 1)}%",
            "Generated By": current_user.full_name
        }
        title = f"{sprint_name} Velocity & Burndown"

    return {
        "report_type": rtype,
        "title": title,
        "project_id": p_id,
        "project_name": p_name,
        "sprint_id": sprint.id if sprint else None,
        "sprint_name": sprint.name if sprint else None,
        "summary": summary,
        "headers": headers,
        "rows": rows,
        "chart_data": chart_data
    }

@router.get("")
def list_reports(db: Session = Depends(get_db), current_user: Profile = Depends(get_current_user)):
    reports = db.query(Report).order_by(Report.created_at.desc()).limit(20).all()
    res = []
    for r in reports:
        gen = db.query(Profile).filter(Profile.id == r.generated_by).first() if r.generated_by else None
        res.append({
            "id": r.id,
            "title": r.title,
            "report_type": r.report_type,
            "format": r.format,
            "generated_by_name": gen.full_name if gen else "System",
            "created_at": r.created_at
        })
    return res

@router.get("/preview")
def get_report_preview(
    report_type: str = Query("SPRINT"),
    project_id: Optional[str] = Query(None),
    sprint_id: Optional[str] = Query(None),
    db: Session = Depends(get_db),
    current_user: Profile = Depends(get_current_user)
):
    """Provides real-time aggregated preview data and charts for the selected report filters."""
    payload = _build_report_payload(db, report_type, project_id, sprint_id, current_user)
    return payload

@router.post("/generate")
def generate_report(req: ReportGenerateRequest, db: Session = Depends(get_db), current_user: Profile = Depends(get_current_user)):
    payload = _build_report_payload(db, req.report_type, req.project_id, req.sprint_id, current_user)
    
    headers = payload["headers"]
    table_rows = payload["rows"]
    summary = payload["summary"]
    report_title = req.title or payload["title"]

    file_format = req.format.upper()
    now_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")

    report_record = Report(
        title=report_title,
        report_type=req.report_type,
        format=file_format,
        generated_by=current_user.id,
        meta_data={"row_count": len(table_rows), "project_id": req.project_id, "sprint_id": req.sprint_id}
    )
    db.add(report_record)
    db.commit()

    safe_filename = report_title.replace(' ', '_').replace('/', '_')

    if file_format == "CSV":
        csv_data = ReportService.generate_csv_report(report_title, headers, table_rows)
        return Response(
            content=csv_data,
            media_type="text/csv",
            headers={"Content-Disposition": f"attachment; filename={safe_filename}.csv"}
        )
    elif file_format == "EXCEL":
        excel_data = ReportService.generate_excel_report(report_title, headers, table_rows)
        return Response(
            content=excel_data,
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": f"attachment; filename={safe_filename}.xlsx"}
        )
    else: # PDF
        pdf_data = ReportService.generate_pdf_report(report_title, now_str, summary, headers, table_rows)
        return Response(
            content=pdf_data,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename={safe_filename}.pdf"}
        )
