import React, { useEffect, useState } from 'react';
import { GlassCard } from '../../components/common/GlassCard';
import { Button } from '../../components/common/Button';
import { Badge } from '../../components/common/Badge';
import { Modal } from '../../components/common/Modal';
import { sprintService, managerService, projectService, taskService, aiService } from '../../services/api';
import { Sprint, Project, AISprintPlan } from '../../types';
import { Layers, Plus, Calendar, Target, CheckCircle2, Sparkles, UserCheck, Flame, FolderKanban } from 'lucide-react';

export const SprintPlanner: React.FC = () => {
  const [sprints, setSprints] = useState<Sprint[]>([]);
  const [projects, setProjects] = useState<any[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isAiModalOpen, setIsAiModalOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [isGeneratingAi, setIsGeneratingAi] = useState(false);
  const [isApplyingAi, setIsApplyingAi] = useState(false);
  const [aiPlan, setAiPlan] = useState<AISprintPlan | null>(null);
  const [aiError, setAiError] = useState<string | null>(null);

  // Form State
  const [name, setName] = useState('');
  const [goal, setGoal] = useState('');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [projectId, setProjectId] = useState('');
  const [selectedFilterProject, setSelectedFilterProject] = useState<string>('ALL');

  const loadData = async () => {
    setIsLoading(true);
    try {
      let pList: any[] = [];
      try {
        pList = await managerService.getProjects();
      } catch (e) {
        console.warn("managerService.getProjects failed, trying projectService.getAll()", e);
      }
      if (!pList || pList.length === 0) {
        try {
          pList = await projectService.getAll();
        } catch (e) {
          console.error("projectService.getAll failed", e);
        }
      }
      setProjects(pList || []);
      
      const sList = await sprintService.getAll();
      setSprints(sList || []);

      if (pList && pList.length > 0 && !projectId) {
        setProjectId(pList[0].id);
      }
    } catch (e) {
      console.error("Failed to load sprints/projects", e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadData();
    const handleMutation = (e: any) => {
      if (e.detail?.entity === 'sprints' || e.detail?.entity === 'tasks' || e.detail?.entity === 'projects') {
        loadData();
      }
    };
    window.addEventListener('sprintiq:mutation', handleMutation);
    return () => window.removeEventListener('sprintiq:mutation', handleMutation);
  }, []);

  const handleCreateSprint = async (e: React.FormEvent) => {
    e.preventDefault();
    const targetProjId = projectId || (projects.length > 0 ? projects[0].id : '');
    if (!targetProjId) {
      alert("Please select a target project first.");
      return;
    }
    try {
      await sprintService.create({
        name,
        goal,
        start_date: startDate,
        end_date: endDate,
        project_id: targetProjId,
      });
      setIsModalOpen(false);
      setName('');
      setGoal('');
      setStartDate('');
      setEndDate('');
      loadData();
    } catch (err: any) {
      alert(err?.response?.data?.detail || "Failed to create sprint.");
    }
  };

  const handleGenerateAiSprint = async () => {
    const targetProjId = projectId || (projects.length > 0 ? projects[0].id : '');
    if (!targetProjId) {
      setAiError("Please select a project before generating a sprint plan.");
      return;
    }
    setIsGeneratingAi(true);
    setAiError(null);
    try {
      const res = await aiService.planSprint({ project_id: targetProjId, target_focus: "Velocity & Feature Delivery" });
      setAiPlan(res);
    } catch (e: any) {
      setAiError(e?.response?.data?.detail || "AI Sprint Planning failed. Please try again.");
    } finally {
      setIsGeneratingAi(false);
    }
  };

  const handleApplyAiSprint = async () => {
    const targetProjId = projectId || (projects.length > 0 ? projects[0].id : '');
    if (!aiPlan || !targetProjId) return;
    setIsApplyingAi(true);
    try {
      const newSprint = await sprintService.create({
        name: `Sprint AI - ${aiPlan.goal.slice(0, 30)}...`,
        goal: aiPlan.goal,
        start_date: new Date().toISOString().split('T')[0],
        end_date: aiPlan.estimated_completion_date || new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
        project_id: targetProjId,
      });

      if (aiPlan.recommended_tasks && aiPlan.recommended_tasks.length > 0) {
        for (const t of aiPlan.recommended_tasks) {
          try {
            await taskService.create({
              title: t.title,
              description: `Generated by Gemini AI Sprint Planner for goal: ${aiPlan.goal}`,
              priority: t.priority || 'MEDIUM',
              story_points: t.story_points || 3,
              estimated_hours: t.estimated_hours || 8.0,
              project_id: targetProjId,
              sprint_id: newSprint.id,
            });
          } catch (taskErr) {
            console.warn("Failed to create recommended task:", taskErr);
          }
        }
      }

      setIsAiModalOpen(false);
      setAiPlan(null);
      loadData();
    } catch (e: any) {
      alert(e?.response?.data?.detail || "Failed to apply AI Sprint");
    } finally {
      setIsApplyingAi(false);
    }
  };

  const displayedSprints = sprints.filter(s => {
    if (selectedFilterProject === 'ALL') return true;
    return s.project_id === selectedFilterProject;
  });

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight flex items-center gap-3">
            AI Sprint Planner <Badge variant="ai">Gemini Powered</Badge>
          </h1>
          <p className="text-xs text-slate-500 mt-1">Plan sprint goals, generate AI story point allocation, and manage active sprint milestones</p>
        </div>

        <div className="flex items-center gap-3 flex-wrap">
          {projects.length > 1 && (
            <select
              value={selectedFilterProject}
              onChange={(e) => setSelectedFilterProject(e.target.value)}
              className="px-3 py-2 rounded-xl text-xs font-semibold bg-white border border-slate-200 text-slate-800 focus:outline-none"
            >
              <option value="ALL">All Projects ({projects.length})</option>
              {projects.map((p) => (
                <option key={p.id} value={p.id}>{p.name}</option>
              ))}
            </select>
          )}
          <Button variant="ai" icon={<Sparkles className="w-4 h-4" />} onClick={() => { setAiError(null); setIsAiModalOpen(true); }}>
            AI Sprint Generator
          </Button>
          <Button variant="outline" icon={<Plus className="w-4 h-4" />} onClick={() => setIsModalOpen(true)}>
            Manual Sprint
          </Button>
        </div>
      </div>

      {isLoading ? (
        <div className="text-center text-slate-400 py-12">Loading sprint planner...</div>
      ) : displayedSprints.length === 0 ? (
        <GlassCard className="!p-12 text-center">
          <FolderKanban className="w-10 h-10 mx-auto mb-3 text-slate-400" />
          <h3 className="text-base font-bold text-slate-900">No Sprints Found</h3>
          <p className="text-xs text-slate-500 mt-1 mb-4">Click "AI Sprint Generator" to create your first intelligent sprint plan with Gemini.</p>
          <Button variant="ai" icon={<Sparkles className="w-4 h-4" />} onClick={() => setIsAiModalOpen(true)}>
            Create AI Sprint Plan
          </Button>
        </GlassCard>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
          {displayedSprints.map((s) => {
            const derived = s.derived_status || s.status;
            const isCompleted = derived === 'COMPLETED';
            const progress = s.progress_percentage || 0;
            const remaining = (s.total_tasks || 0) - (s.completed_tasks || 0);

            return (
              <GlassCard key={s.id} hoverEffect className="border-l-4 border-l-emerald-500 space-y-4 flex flex-col">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    {isCompleted && <CheckCircle2 className="w-5 h-5 text-emerald-500" />}
                    <Badge variant={
                      derived === 'COMPLETED' ? 'completed' :
                        derived === 'OVERDUE' ? 'critical' :
                          derived === 'ACTIVE' ? 'in_progress' :
                            derived === 'CANCELLED' ? 'default' : 'pending'
                    }>{derived}</Badge>
                  </div>
                  <span className="text-xs text-slate-500 font-mono">{s.start_date} to {s.end_date}</span>
                </div>

                <div>
                  <h3 className="text-lg font-bold text-slate-900 mb-1">{s.name}</h3>
                  <p className="text-slate-600 text-xs flex items-start gap-1.5 leading-relaxed">
                    <Target className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                    <span>{s.goal || "No explicit goal set."}</span>
                  </p>
                </div>

                <div className="mt-auto pt-4 border-t border-slate-100 w-full">
                  <div className="flex justify-between text-[11px] text-slate-500 mb-1 font-medium">
                    <span>Progress: {progress}%</span>
                    <span>{s.completed_tasks || 0} / {s.total_tasks || 0} Tasks Completed</span>
                  </div>
                  <div className="w-full bg-slate-100 rounded-full h-2 mb-2 overflow-hidden">
                    <div className="bg-emerald-500 h-2 rounded-full transition-all duration-300" style={{ width: `${progress}%` }} />
                  </div>

                  {isCompleted ? (
                    <p className="text-[10px] text-emerald-600 font-bold flex items-center justify-end gap-1">
                      <CheckCircle2 className="w-3 h-3" /> All tasks verified by manager
                    </p>
                  ) : (
                    <p className="text-[10px] text-slate-400 text-right">
                      {s.total_tasks === 0 ? "No tasks assigned" : `Remaining: ${remaining} Tasks | Rejected: ${s.rejected_tasks || 0}`}
                    </p>
                  )}
                </div>
              </GlassCard>
            );
          })}
        </div>
      )}

      {/* Manual Sprint Modal */}
      <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title="Create New Sprint">
        <form onSubmit={handleCreateSprint} className="space-y-4">
          <div>
            <label className="block text-xs font-semibold text-slate-600 mb-1">Target Project</label>
            <select
              value={projectId}
              onChange={(e) => setProjectId(e.target.value)}
              className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-200 text-slate-900 text-xs"
            >
              {projects.map((p) => (
                <option key={p.id} value={p.id}>{p.name} ({p.key || 'PROJ'})</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-600 mb-1">Sprint Name</label>
            <input
              type="text"
              required
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. Sprint 2 - User Onboarding"
              className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-200 text-slate-900 text-xs"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-600 mb-1">Sprint Goal</label>
            <textarea
              rows={2}
              value={goal}
              onChange={(e) => setGoal(e.target.value)}
              placeholder="Primary milestone target..."
              className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-200 text-slate-900 text-xs"
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold text-slate-600 mb-1">Start Date</label>
              <input
                type="date"
                required
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-200 text-slate-900 text-xs"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-600 mb-1">End Date</label>
              <input
                type="date"
                required
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-200 text-slate-900 text-xs"
              />
            </div>
          </div>

          <div className="flex justify-end gap-3 pt-2">
            <Button type="button" variant="outline" onClick={() => setIsModalOpen(false)}>Cancel</Button>
            <Button type="submit" variant="manager">Create Sprint</Button>
          </div>
        </form>
      </Modal>

      {/* AI Sprint Generator Modal */}
      <Modal isOpen={isAiModalOpen} onClose={() => setIsAiModalOpen(false)} title="AI Sprint Planner (Gemini Suggested)" maxWidth="max-w-2xl">
        <div className="space-y-4">
          <p className="text-xs text-slate-500">Gemini analyzes project history, velocity, and backlog to suggest optimal sprint goals, story points, duration, developers, and workload distribution.</p>

          <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 space-y-3">
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">Target Project</label>
              <select
                value={projectId}
                onChange={(e) => setProjectId(e.target.value)}
                className="w-full px-3.5 py-2 rounded-xl bg-white border border-slate-300 text-slate-900 text-xs font-medium"
              >
                {projects.map((p) => (
                  <option key={p.id} value={p.id}>{p.name} ({p.key || 'PROJ'})</option>
                ))}
              </select>
            </div>

            <div className="flex justify-between items-center pt-1">
              <Button variant="ai" onClick={handleGenerateAiSprint} isLoading={isGeneratingAi} icon={<Sparkles className="w-4 h-4" />}>
                Generate AI Sprint Plan
              </Button>
            </div>
          </div>

          {aiError && (
            <div className="p-3 bg-rose-50 text-rose-700 border border-rose-200 rounded-xl text-xs">
              {aiError}
            </div>
          )}

          {aiPlan && (
            <div className="space-y-4 p-4 rounded-xl bg-slate-50 border border-slate-200 text-xs">
              <div className="border-b border-slate-200 pb-3">
                <p className="font-bold text-slate-900 text-sm">Suggested Goal:</p>
                <p className="text-emerald-600 font-medium mt-1 leading-relaxed">{aiPlan.goal}</p>
              </div>

              <div className="grid grid-cols-3 gap-3 text-slate-600 bg-white p-3 rounded-lg border border-slate-200">
                <div>Duration: <strong className="text-slate-900 block mt-0.5">{aiPlan.duration_weeks} Weeks</strong></div>
                <div>Total Points: <strong className="text-emerald-600 block mt-0.5">{aiPlan.total_story_points} SP</strong></div>
                <div>Est. Completion: <strong className="text-slate-900 block mt-0.5">{aiPlan.estimated_completion_date}</strong></div>
              </div>

              <div>
                <p className="font-semibold text-slate-900 mb-2">Recommended Backlog Tasks ({aiPlan.recommended_tasks?.length || 0}):</p>
                <div className="space-y-2 max-h-56 overflow-y-auto pr-1">
                  {aiPlan.recommended_tasks?.map((t, idx) => (
                    <div key={idx} className="p-2.5 rounded-lg bg-white border border-slate-200 flex items-center justify-between text-xs">
                      <span className="font-semibold text-slate-800">{t.title}</span>
                      <div className="flex gap-2">
                        <span className="px-2 py-0.5 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 font-semibold">{t.story_points} SP</span>
                        <span className="px-2 py-0.5 rounded bg-blue-50 text-blue-700 border border-blue-200 font-semibold">{t.priority}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="flex justify-end pt-2 border-t border-slate-200">
                <Button variant="ai" onClick={handleApplyAiSprint} isLoading={isApplyingAi} icon={<CheckCircle2 className="w-4 h-4" />}>
                  1-Click Apply AI Sprint Plan & Tasks
                </Button>
              </div>
            </div>
          )}
        </div>
      </Modal>
    </div>
  );
};
